apiVersion: apps/v1
kind: Deployment
metadata:
  name: bkjbvff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bkjbvff
  template:
    metadata:
      labels:
        app: bkjbvff
    spec:
      containers:
      - image: okteto.dev/bkjbvff:latest
        name: bkjbvff
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "805509f0-de71-61d2-9f2b-21982b6fdab6"
        - name: Vless_Path
          value: "/vyuiyl555"
        - name: Vmess_UUID
          value: "805509f0-de71-61d2-9f2b-21982b6fdab6"
        - name: Vmess_Path
          value: "/vmtyrfs666"
        - name: Share_Path
          value: "/v2link"
