apiVersion: apps/v1
kind: Deployment
metadata:
  name: gjvtyee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gjvtyee
  template:
    metadata:
      labels:
        app: gjvtyee
    spec:
      containers:
      - image: okteto.dev/gjvtyee:latest
        name: gjvtyee
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c4b2954b-4b27-81d8-a8ad-e9aeab504ada"
        - name: Vless_Path
          value: "/vyuiyl555"
        - name: Vmess_UUID
          value: "c4b2954b-4b27-81d8-a8ad-e9aeab504ada"
        - name: Vmess_Path
          value: "/vmtyrfs666"
        - name: Share_Path
          value: "/v2link"
